[program:schedule-ticker]
directory    = /var/www
command      = /usr/bin/php vendor/bin/naf schedule:ticker
priority     = 40
autostart    = %(ENV_NAFINITY_BACKGROUND_ENABLED)s
autorestart  = true
startsecs    = 3
startretries = 10
stopsignal   = TERM
stopwaitsecs = 30
stopasgroup  = true
killasgroup  = true

stdout_logfile          = /dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile          = /dev/stderr
stderr_logfile_maxbytes = 0
