[program:websocket]
directory    = /var/www
command      = /usr/bin/php vendor/bin/naf websocket:serve
priority     = 40
autostart    = %(ENV_WEBSOCKET_ENABLED)s
autorestart  = true
startsecs    = 3
startretries = 10
stopsignal   = TERM
stopwaitsecs = 5
stopasgroup  = true
killasgroup  = true

stdout_logfile          = /dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile          = /dev/stderr
stderr_logfile_maxbytes = 0
